from dotenv import load_dotenv
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_core.prompts import PromptTemplate

load_dotenv()

_model = None

# ---------- Create LLM ----------
def create_llm():
    """
    Creates and returns the chat model.
    """
    global _model
    
    if _model is None:
        llm = HuggingFaceEndpoint(
            repo_id="meta-llama/Llama-3.1-8B-Instruct",
            task="text-generation",
            temperature=0.2,
        )
        _model = ChatHuggingFace(llm=llm)
    return _model

# ---------- Prompt Template ----------

def get_prompt():
    """
    Returns the RAG prompt template.
    """

    prompt = PromptTemplate(
        template=""" 
        You are a helpful assistant.
        Answer the user's question ONLY using the transcript context provided below.
        If the question is not related to the transcript provided, generate answer only when you are 100 percent sure.
        Do not hallucinate and for every generated answer, give the confidence score.
        do not generate confidence score for closing sentence like thank you. 
        
        Context:
        {context}
        
        Question:
        {query}
        """,
        
        input_variables=["context", "query"]
    )

    return prompt

# ---------- Answer Query ----------

def answer_query(query, retriever):
    """
    Complete RAG pipeline.

    Parameters:
        query (str): User question
        retriever: LangChain retriever object

    Returns:
        str: Final answer generated by the LLM
    """

    # Retrieve relevant chunks
    retrieved_docs = retriever.invoke(query)

    # Build context
    context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)

    # Prompt
    prompt = get_prompt()

    final_prompt = prompt.invoke({"context": context_text, "query": query})

    # LLM
    model = create_llm()

    # Generate answer
    response = model.invoke(final_prompt)

    return response.content