from dotenv import load_dotenv
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_core.prompts import PromptTemplate

load_dotenv()

_model = None

# ---------- Create LLM ----------
def create_llm():
    """
    Creates and returns the chat model.
    """
    global _model
    
    if _model is None:
        llm = HuggingFaceEndpoint(
            repo_id="meta-llama/Llama-3.1-8B-Instruct",
            task="text-generation",
            temperature=0.2,
        )
        _model = ChatHuggingFace(llm=llm)
    return _model

# ---------- Prompt Template ----------

def get_prompt():
    """
    Returns the RAG prompt template.
    """

    prompt = PromptTemplate(
        template=""" 
        You are a helpful assistant.
        Use the transcript context as the primary source of information.
        Use the conversation history only to understand references such as:
        - it
        - that
        - this concept
        - the previous answer
        
        Do not treat repeated topics as repeated questions.
        
        Do not claim that the user has asked a question before unless it explicitly appears in the conversation history.
        
        If the answer is not found in the transcript context, reply:
        'I don't know'.
        
        Conversation history:
        {history}
        
        Context:
        {context}
        
        Question:
        {query}
        
        Answer:
        """,
        
        input_variables=["history", "context", "query"]
    )

    return prompt

def format_chat_history(chat_history):

    history = []

    for message in chat_history:

        role = message["role"].capitalize()

        history.append(
            f"{role}: {message['content']}"
        )

    return "\n".join(history)

# ---------- Answer Query ----------

def answer_query(query, retriever, chat_history):
    """
    Complete RAG pipeline.

    Parameters:
        query (str): User question
        retriever: LangChain retriever object

    Returns:
        str: Final answer generated by the LLM
    """

    # Retrieve relevant chunks
    retrieved_docs = retriever.invoke(query)
    
    if not retrieved_docs:
        return "I Don't know."

    # Build context
    context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
    
    history_text = format_chat_history(chat_history[-6:])

    # Prompt
    prompt = get_prompt()

    final_prompt = prompt.invoke({"history": history_text,"context": context_text, "query": query})

    # LLM
    model = create_llm()

    # Generate answer
    response = model.invoke(final_prompt)

    return response.content